### ISSUE TITLE
Heat demand

### ISSUE THREAD

**Issue by michass** [mvzut/maxcube-Domoticz-plugin#2]
Please describe, what Heat demand is, and what to use it?

**Comment by Freekers** [comment]
Judging from the code, I think it means when one (or more) thermostatic radiator valves are below their set target temperature. Therefore they are in a state of 'demand for heat' a.k.a. 'hey it's cold in here, send us some hot water'. When a thermostatic radiator valve is in a demand heat state, it's valve is open by at least 25% or more.

**Comment by mvzut** [comment]
This is correct.

Please note that the discussion about the heat demand switch and other aspects of the plugin is taking place on the Domoticz forum (see link in README.md), I just use GitHub for hosting the files.
